import '../../data/models/item_models.dart';
import '../../data/models/event_models.dart';

final List<EventDefinition> kGameEvents = [
  const EventDefinition(
    id: 'first_home',
    triggerDay: 1,
    title: 'Новый домик',
    description: 'Финни нашёл мяч. Возьмём его домой?',
    icon: '🏡',
    choices: [
      EventChoice(
        id: 'first_ball',
        title: 'Купить мяч · 10 🪙',
        cost: 10,
        expenseCategory: ItemCategory.want,
        grantItemId: 'toy_ball',
        immediateFeedback: 'Мяч появится в домике · ❤️+.',
        consequenceText: 'Мяч уже в комнате. Нажми на него!',
        moodEffect: FinnyMood.happy,
        wellbeing: 1,
      ),
      EventChoice(
        id: 'first_save',
        title: 'Сохранить монеты',
        cost: 0,
        immediateFeedback: 'Монеты останутся на еду или мечту.',
        consequenceText: 'Финни решил сначала освоиться в домике.',
        moodEffect: FinnyMood.good,
      ),
    ],
  ),
  const EventDefinition(
    id: 'market_find',
    triggerDay: 2,
    title: 'Прилавок у дома',
    description: 'Сосед продаёт два завтрака за 11 🪙.',
    icon: '🍎',
    choices: [
      EventChoice(
        id: 'market_food',
        title: 'Купить еду · 11 🪙',
        cost: 11,
        expenseCategory: ItemCategory.need,
        foodReserveChange: 2,
        immediateFeedback: 'Монеты −11 · два завтрака в кладовке.',
        consequenceText: 'В кладовке появились два завтрака.',
        moodEffect: FinnyMood.good,
      ),
      EventChoice(
        id: 'market_wait',
        title: 'Пока не покупать',
        cost: 0,
        immediateFeedback: 'Сохранишь монеты, еду можно купить позже.',
        consequenceText: 'Финни решил подумать о других покупках.',
        moodEffect: FinnyMood.normal,
      ),
    ],
  ),
  const EventDefinition(
    id: 'garden_help',
    triggerDay: 3,
    title: 'Помощь в саду',
    description: 'Финни помог соседке. Что взять за работу?',
    icon: '🌱',
    choices: [
      EventChoice(
        id: 'garden_coins',
        title: 'Взять оплату',
        cost: 0,
        reward: 8,
        immediateFeedback: '🪙+8 · ⚡− 🍽️−.',
        consequenceText: 'Соседка заплатила 8 🪙 за помощь в саду.',
        moodEffect: FinnyMood.good,
        satiety: -1,
        energy: -1,
      ),
      EventChoice(
        id: 'garden_food',
        title: 'Взять два завтрака',
        cost: 0,
        foodReserveChange: 2,
        immediateFeedback: 'В кладовке станет на 2 порции больше.',
        consequenceText: 'Финни принёс домой два завтрака вместо монет.',
        moodEffect: FinnyMood.happy,
      ),
    ],
  ),
  const EventDefinition(
    id: 'storm_warning',
    triggerDay: 4,
    title: 'Завтра ливень',
    description: 'Сосед предлагает набор для ремонта крыши. Подготовимся?',
    icon: '🌧️',
    choices: [
      EventChoice(
        id: 'prepare_kit',
        title: 'Купить набор мастера',
        cost: 15,
        expenseCategory: ItemCategory.reserve,
        grantItemId: 'repair_kit',
        immediateFeedback:
            'Сегодня −15 🪙. Если крыша потечёт, набор поможет без доплаты.',
        consequenceText: 'Набор мастера лежит дома на случай ливня.',
        moodEffect: FinnyMood.good,
      ),
      EventChoice(
        id: 'keep_storm_money',
        title: 'Сохранить монеты',
        cost: 0,
        immediateFeedback:
            'Монеты останутся. Завтра выберешь, что делать с крышей.',
        consequenceText: 'Финни решил дождаться прогноза и сохранить деньги.',
        moodEffect: FinnyMood.normal,
      ),
    ],
  ),
  const EventDefinition(
    id: 'rain_roof',
    triggerDay: 5,
    title: 'Крыша протекает',
    description: 'После ливня в домике закапало. Выбери, как помочь Финни.',
    icon: '🌧️',
    choices: [
      EventChoice(
        id: 'repair_now',
        title: 'Починить крышу',
        cost: 25,
        expenseCategory: ItemCategory.reserve,
        freeWithItemId: 'repair_kit',
        immediateFeedback: 'Крыша станет сухой · ❤️+.',
        consequenceText: 'В домике снова сухо. Ремонт стоил 25 🪙.',
        moodEffect: FinnyMood.good,
        wellbeing: 1,
      ),
      EventChoice(
        id: 'patch_roof',
        title: 'Сделать заплатку',
        cost: 8,
        expenseCategory: ItemCategory.reserve,
        immediateFeedback: 'Сегодня капли остановятся.',
        consequenceText: 'Сегодня сухо. Позже крышу надо проверить снова.',
        moodEffect: FinnyMood.normal,
      ),
      EventChoice(
        id: 'ignore_roof',
        title: 'Подставить тазик',
        cost: 0,
        immediateFeedback: 'Монеты останутся · ❤️−.',
        consequenceText:
            'Монеты целы. Крышу всё равно придётся починить позже.',
        moodEffect: FinnyMood.worried,
        wellbeing: -1,
      ),
    ],
  ),
  const EventDefinition(
    id: 'lantern_workshop',
    triggerDay: 6,
    title: 'Мастерская фонарей',
    description: 'Финни помог собрать фонарь. Что взять за работу?',
    icon: '💡',
    choices: [
      EventChoice(
        id: 'lantern_gift',
        title: 'Фонарь для домика',
        cost: 0,
        grantItemId: 'warm_lamp',
        immediateFeedback:
            'Фонарь появится в комнате. Монет за работу не будет.',
        consequenceText: 'В комнате Финни появился новый фонарь.',
        moodEffect: FinnyMood.happy,
        wellbeing: 1,
      ),
      EventChoice(
        id: 'lantern_pay',
        title: 'Взять 10 🪙',
        cost: 0,
        reward: 10,
        immediateFeedback: '🪙+10 · ⚡− 🍽️−.',
        consequenceText: 'Финни получил 10 🪙 за помощь в мастерской.',
        moodEffect: FinnyMood.good,
        satiety: -1,
        energy: -1,
      ),
    ],
  ),
  const EventDefinition(
    id: 'festival_preview',
    triggerDay: 7,
    title: 'Билет заранее',
    description: 'Завтра карусели. Сегодня билет дешевле.',
    icon: '🎟️',
    choices: [
      EventChoice(
        id: 'early_ticket',
        title: 'Купить билет за 12',
        cost: 12,
        expenseCategory: ItemCategory.want,
        grantItemId: 'festival_ticket',
        immediateFeedback: 'Сегодня −12 🪙. Завтра карусель уже оплачена.',
        consequenceText: 'Билет на завтрашний праздник ждёт Финни.',
        moodEffect: FinnyMood.happy,
      ),
      EventChoice(
        id: 'decide_tomorrow',
        title: 'Решить завтра',
        cost: 0,
        immediateFeedback: 'Монеты останутся. Завтра билет будет стоить 15 🪙.',
        consequenceText: 'Финни сохранил свободу выбора до завтра.',
        moodEffect: FinnyMood.good,
      ),
    ],
  ),
  const EventDefinition(
    id: 'city_festival',
    triggerDay: 8,
    title: 'Праздник в городе',
    description: 'На площади музыка и карусели. Как проведём день?',
    icon: '🎪',
    choices: [
      EventChoice(
        id: 'buy_ticket',
        title: 'Пойти на карусели',
        cost: 15,
        expenseCategory: ItemCategory.want,
        freeWithItemId: 'festival_ticket',
        immediateFeedback: '❤️+ ⚡− 🍽️−.',
        consequenceText: 'Финни прокатился на каруселях и остался доволен.',
        moodEffect: FinnyMood.happy,
        satiety: -1,
        energy: -1,
        wellbeing: 2,
      ),
      EventChoice(
        id: 'free_walk',
        title: 'Послушать концерт',
        cost: 0,
        immediateFeedback: 'Бесплатно · ❤️+ ⚡−.',
        consequenceText:
            'Финни послушал музыку. Монеты остались для других планов.',
        moodEffect: FinnyMood.good,
        energy: -1,
        wellbeing: 1,
      ),
    ],
  ),
  const EventDefinition(
    id: 'windy_gift',
    triggerDay: 9,
    title: 'Подарок за помощь',
    description: 'Финни помог убрать площадь после праздника. Выбирай награду.',
    icon: '🪁',
    choices: [
      EventChoice(
        id: 'kite_gift',
        title: 'Воздушный змей',
        cost: 0,
        grantItemId: 'kite',
        immediateFeedback:
            'Змей поселится в домике. Монеты за помощь не дадут.',
        consequenceText: 'В домике появился воздушный змей для игр.',
        moodEffect: FinnyMood.happy,
        wellbeing: 1,
      ),
      EventChoice(
        id: 'windy_pay',
        title: 'Взять 12 🪙',
        cost: 0,
        reward: 12,
        immediateFeedback: '🪙+12 · ⚡− 🍽️−.',
        consequenceText: 'Финни получил 12 🪙 за помощь на площади.',
        moodEffect: FinnyMood.good,
        satiety: -1,
        energy: -1,
      ),
    ],
  ),
  const EventDefinition(
    id: 'last_day',
    triggerDay: 10,
    title: 'День важных решений',
    description: 'Сосед снова просит помочь. Что важнее сейчас?',
    icon: '🌟',
    choices: [
      EventChoice(
        id: 'last_help',
        title: 'Помочь · +8 🪙',
        cost: 0,
        reward: 8,
        immediateFeedback: 'Монеты +8 · силы и сытость снизятся.',
        consequenceText: 'Финни помог соседу и получил 8 🪙.',
        moodEffect: FinnyMood.good,
        satiety: -1,
        energy: -1,
      ),
      EventChoice(
        id: 'last_rest',
        title: 'Побыть дома',
        cost: 0,
        immediateFeedback: '⚡+ ❤️+.',
        consequenceText: 'Финни провёл время в уютном домике.',
        moodEffect: FinnyMood.happy,
        energy: 2,
        wellbeing: 1,
      ),
    ],
  ),
];
