import '../../data/models/item_models.dart';

final List<ShopItem> kShopCatalog = [
  const ShopItem(
    id: 'food_1',
    name: 'Яблоко и сытная каша',
    icon: '🍎',
    price: 7,
    category: ItemCategory.need,
    description: 'Одна порция еды для Финни.',
    immediateEffect: 'В кладовке будет ещё одна порция.',
    practicalUse: 'На карточке еды восполнит сытость.',
    foodDaysProvided: 1,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'food_3',
    name: 'Корзинка продуктов',
    icon: '🧺',
    price: 18,
    category: ItemCategory.reserve,
    description: 'Три порции еды со скидкой 3 🪙!',
    immediateEffect: 'В кладовке станет на три порции больше.',
    practicalUse: 'Выгода 3 🪙 по сравнению с покупкой по одной порции.',
    foodDaysProvided: 3,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'food_5',
    name: 'Большая кладовая',
    icon: '📦',
    price: 27,
    category: ItemCategory.reserve,
    description: 'Пять порций еды со скидкой 8 🪙!',
    immediateEffect: 'В кладовке станет на пять порций больше.',
    practicalUse: 'Самая выгодная оптовая покупка: экономия 8 🪙.',
    foodDaysProvided: 5,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'raincoat',
    name: 'Жёлтый дождевик',
    icon: '🧥',
    price: 12,
    category: ItemCategory.reserve,
    description: 'Непромокаемый яркий дождевик для Финни.',
    immediateEffect: 'Финни готов к прогулкам под дождём.',
    practicalUse:
        'С дождевиком прогулка под дождём радует Финни и бережёт здоровье.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'repair_kit',
    name: 'Набор мастера',
    icon: '🧰',
    price: 15,
    category: ItemCategory.reserve,
    description: 'Молоток, доски и гвозди на случай протечки крыши.',
    immediateEffect: 'Всегда под рукой в кладовке.',
    practicalUse:
        'При протечке крыши ремонт без доплаты. Набор используется один раз.',
    foodDaysProvided: 0,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'toy_ball',
    name: 'Прыгучий мячик',
    icon: '⚽',
    price: 10,
    category: ItemCategory.want,
    description: 'Яркий мяч, который весело отскакивает от пола.',
    immediateEffect: 'Финни очень весело гоняет мячик по комнате!',
    practicalUse: 'Нажми в комнате: ❤️+ ⚡−. Одно действие с вещами в день.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'toy_robot',
    name: 'Заводной робот',
    icon: '🤖',
    price: 22,
    category: ItemCategory.want,
    description: 'Умеет ходить, крутить шестеренками и мигать глазами.',
    immediateEffect: 'Восторг! Финни не может оторваться от игры.',
    practicalUse: 'Нажми в комнате: ❤️+ ⚡−. Одно действие с вещами в день.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'cozy_bed',
    name: 'Мягкая лежанка',
    icon: '🛏',
    price: 25,
    category: ItemCategory.useful,
    description: 'Тёплая плюшевая постелька с подушечкой.',
    immediateEffect: 'Уютное место для отдыха Финни.',
    practicalUse: 'Нажми в комнате: ⚡+. Одно действие с вещами в день.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'warm_lamp',
    name: 'Настольная лампа',
    icon: '💡',
    price: 12,
    category: ItemCategory.useful,
    description: 'Мягкий золотистый свет для уютных вечеров.',
    immediateEffect: 'В комнате становится тепло и уютно.',
    practicalUse: 'Нажми в комнате: ❤️+. Одно действие с вещами в день.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'kite',
    name: 'Воздушный змей',
    icon: '🪁',
    price: 18,
    category: ItemCategory.want,
    description: 'Летающий дракончик с разноцветным хвостом.',
    immediateEffect: 'Финни с радостью запускает змея в небо.',
    practicalUse:
        'Без дождя нажми в комнате: ❤️+ ⚡−. Одно действие с вещами в день.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
];
