import '../../data/models/item_models.dart';

final List<ShopItem> kShopCatalog = [
  const ShopItem(
    id: 'food_1',
    name: 'Яблоко и сытная каша',
    icon: '🍎',
    price: 7,
    category: ItemCategory.need,
    description: 'Вкусный и полезный завтрак на 1 день.',
    immediateEffect: 'Финни сыт и доволен сегодня.',
    practicalUse: 'Обеспечивает сытость на 1 день.',
    foodDaysProvided: 1,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'food_3',
    name: 'Корзинка продуктов',
    icon: '🧺',
    price: 18,
    category: ItemCategory.reserve,
    description: 'Набор еды на 3 дня со скидкой 3 монеты!',
    immediateEffect: 'Запасы еды пополнены на 3 дня.',
    practicalUse: 'Выгода 3 монеты по сравнению с покупкой по 1 дню.',
    foodDaysProvided: 3,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'food_5',
    name: 'Большая кладовая',
    icon: '📦',
    price: 27,
    category: ItemCategory.reserve,
    description: 'Большой запас на 5 дней со скидкой 8 монет!',
    immediateEffect: 'Целых 5 дней можно не думать о еде.',
    practicalUse: 'Самая выгодная оптовая покупка: экономия 8 монет.',
    foodDaysProvided: 5,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'raincoat',
    name: 'Жёлтый дождевик',
    icon: '🧥',
    price: 12,
    category: ItemCategory.reserve,
    description: 'Непромокаемый яркий дождевик для Финни.',
    immediateEffect: 'Финни готов к прогулкам под дождём.',
    practicalUse: 'Защищает от простуды и грусти во время ливня.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'repair_kit',
    name: 'Набор мастера',
    icon: '🧰',
    price: 15,
    category: ItemCategory.reserve,
    description: 'Молоток, доски и гвозди для любого ремонта.',
    immediateEffect: 'Всегда под рукой в кладовке.',
    practicalUse: 'Позволяет мгновенно и бесплатно починить любую поломку в доме.',
    foodDaysProvided: 0,
    isPermanent: false,
  ),
  const ShopItem(
    id: 'toy_ball',
    name: 'Прыгучий мячик',
    icon: '⚽',
    price: 10,
    category: ItemCategory.want,
    description: 'Яркий мяч, который весело отскакивает от пола.',
    immediateEffect: 'Финни очень весело гоняет мячик по комнате!',
    practicalUse: 'Появляется в комнате и радует питомца.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'toy_robot',
    name: 'Заводной робот',
    icon: '🤖',
    price: 22,
    category: ItemCategory.want,
    description: 'Умеет ходить, крутить шестеренками и мигать глазами.',
    immediateEffect: 'Восторг! Финни не может оторваться от игры.',
    practicalUse: 'Украшает комнату и делает Финни счастливым.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'cozy_bed',
    name: 'Мягкая лежанка',
    icon: '🛏',
    price: 25,
    category: ItemCategory.useful,
    description: 'Тёплая плюшевая постелька с подушечкой.',
    immediateEffect: 'Уютное место для отдыха Финни.',
    practicalUse: 'Каждый вечер Финни сладко засыпает в тепле.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'warm_lamp',
    name: 'Настольная лампа',
    icon: '💡',
    price: 12,
    category: ItemCategory.useful,
    description: 'Мягкий золотистый свет для уютных вечеров.',
    immediateEffect: 'В комнате становится тепло и уютно.',
    practicalUse: 'Преображает вечернюю комнату приятным светом.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
  const ShopItem(
    id: 'kite',
    name: 'Воздушный змей',
    icon: '🪁',
    price: 18,
    category: ItemCategory.want,
    description: 'Летающий дракончик с разноцветным хвостом.',
    immediateEffect: 'Финни с радостью запускает змея в небо.',
    practicalUse: 'Приносит море позитивных эмоций на свежем воздухе.',
    foodDaysProvided: 0,
    isPermanent: true,
  ),
];
